services:
  # 1. SERVIÇO DO BANCO DE DADOS (POSTGRESQL)
  - type: pserv
    name: tododb
    region: oregon
    plan: free 
    databaseName: lista_de_tarefas_db 
    
  # 2. SERVIÇO DO BACKEND (DJANGO)
  - type: web 
    name: lista-de-tarefas-api
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn lista_de_tarefas_projeto.wsgi:application"
    healthCheckPath: /api/tasks/stats/
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tododb
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: lista-de-tarefas-api
          property: host
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: lista-de-tarefas-api
          property: url

  # 3. SERVIÇO DO FRONTEND (REACT - Static Site)
  - type: static
    name: lista-de-tarefas-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: "frontend/build" 
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: lista-de-tarefas-api
          property: url